OrgChart.templates.ana.field_0 = '<text class="field_0"  style="font-size: 20px;" fill="#ffffff" x="125" y="30" text-anchor="middle">{val}</text>';
OrgChart.templates.ana.field_1 = '<text class="field_1"  style="font-size: 20px;" fill="#ffffff" x="125" y="50" text-anchor="middle">{val}</text>';
OrgChart.templates.ana.field_2 = '<text class="field_2"  style="font-size: 14px;" fill="#ffffff" x="125" y="70" text-anchor="middle">{val}</text>';
OrgChart.templates.ana.field_3 = '<text class="field_3"  style="font-size: 14px;" fill="#ffffff" x="125" y="90" text-anchor="middle">{val}</text>';

var chart = new OrgChart(document.getElementById("orgchart"), {
    layout: OrgChart.mixed,
    nodeBinding: {
        field_0: "name",
        field_1: "voornaam",
        field_2: "date"
    },
     
});

var jenaoorsprongtree = null;
var peeterstree = null;
var michielstree = null;
var renderstree = null;
var demuldertree = null;
var jenatree = null;

window.onload = (event) => {
    jenaoorsprongtree = [
        { id: 1, name: "Jena", voornaam: "Felix", date: "14/01/1807-07/08/1876", beschrijving: "", tags: ["jena"]},
        { id: 16, pid: 1, tags: ["partner", "verhulst"], name: "Verhulst",voornaam: "Ana Maria",date: "1802-1870"}, 
        { id: 18, pid: 3, tags: ['partner', "verhulst"] , name: "Delqui",voornaam: "Joanna",date: ""},
        { id: 2, pid: 1, ppid: 16, name: "Jena",voornaam: "Joanna Maria",date: "1831-1834",tags: ["jena"]},                
        { id: 3, pid: 1, ppid: 16, name: "Jena",voornaam: "Jan Baptist",date: "02/09/1835-15/02/1910",tags: ["jena"],},
        { id: 4, pid: 1, ppid: 16, name: "Jena",voornaam: "Guillemin Albertus",date: "08/01/1839-16/04/1887",tags: ["jena"]},
        { id: 19, pid: 4, tags: ['partner',"verhulst"], name: "Delmé",voornaam: "Maria Thérésia",date: "1833-09/03/1900" },
        { id: 5, pid: 3, name: " Guns",voornaam: "Jozef",date: "1873" },
        { id: 6, pid: 3, name: "Guns",voornaam: "Virginia ",date: "1860" },
        { id: 7, pid: 3, name: "Guns",voornaam: "Alfonsus ",date: "1867" },
        { id: 8, pid: 3, name: "Guns ",voornaam: "Guilielmus ",date: "1870" },
        { id: 9, pid: 3, name: "Guns",voornaam: "Philistina ",date: "1863" },
        { id: 10, pid: 4, name: "Jena",voornaam: "Guisbertus Augustinus ",date: "1863-1867", tags: ["jena"] },
        { id: 11, pid: 4, name: "Jena",voornaam: "Joanna Maria",date: "1865", tags: ["jena"]},
        { id: 12, pid: 4, name: "Jena",voornaam: "Maria Theresia",date: "1866", tags: ["jena"] },
        { id: 13, pid: 4, name: "Jena",voornaam: "Maria Louisa",date: "21/05/1868", tags: ["jena"] },
        { id: 14, pid: 4, name: "Jena",voornaam: "Stephania",date: "1879", tags: ["jena"] },
        { id: 15, pid: 4, name: "Jena",voornaam: "Emile",date: "1878-1958" , tags: ["jena"]},        
        { id: 20, pid: 11, tags: ['partner',"verhulst"], name: "Peeters",voornaam: "Francois August",date: "1861"},
        { id: 21, pid: 12, tags: ['partner',"verhulst"], name: "Michiels",voornaam: "Constantius",date: "1871"},
        { id: 22, pid: 13, tags: ['partner',"verhulst"], name: "Renders",voornaam: "Joannes Baptista",date: "23/05/1860"},
        { id: 23, pid: 14, tags: ['partner',"verhulst"], name: "De Mulder",voornaam: "Joannes",date: ""},
        { id: 24, pid: 15, tags: ['partner',"verhulst"], name: "Vanderborght",voornaam: "Maria Theresia",date: " "},                 
    ];
    
    peeterstree = [
        { id: 1, name: "Felix", voornaam: "Jena", date: "14/01/1807-07/08/1876", beschrijving: "", tags: ["jena"]},
        { id: 16, pid: 1, tags: ["partner", "Jena"], name: "Verhulst",voornaam: "Anna Maria",date: "1802-1870"}, 
        { id: 18, pid: 3, tags: ['partner', ] , name: "Delqui",voornaam: "Joanna",date: ""},
        { id: 2, pid: 1, ppid: 16, name: "Jena",voornaam: "Joanna Maria",date: "1831-1834"},                
        { id: 3, pid: 1, ppid: 16, name: "Jena",voornaam: "Jan Baptist",date: "02/09/1835-15/02/1910"},
        { id: 4, pid: 1, ppid: 16, name: "Jena",voornaam: "Guillemin Albertus",date: "08/01/1839-16/04/1887", tags: ["jena"]},
        { id: 19, pid: 4, tags: ['partner'], name: "Delmé",voornaam: "Maria Thérésia",date: "1833-09/03/1900" },
        { id: 10, pid: 4, name: "Jena",voornaam: "Guisbertus Augustinus ",date: "1863-1867" },
        { id: 11, pid: 4, name: "Jena",voornaam: "Joanna Maria",date: "1865", tags: ["jena"]},
        { id: 12, pid: 4, name: "Jena",voornaam: "Maria Theresia",date: "1866" },
        { id: 13, pid: 4, name: "Jena",voornaam: "Maria Louisa",date: "21/05/1868" },
        { id: 14, pid: 4, name: "Jena",voornaam: "Stephania",date: "1879" },
        { id: 15, pid: 4, name: "Jena",voornaam: "Emile",date: "1878-1958" },
        { id: 17, pid: 11, ppid:20, name: "Peeters",voornaam: "Maria Theresia",date: "20/05/1890-1914" ,tags: ["jena"]},
        { id: 20, pid: 11, tags: ['partner',"verhulst"], name: "Peeters",voornaam: "Francois August",date: "1861"},
        { id: 21, pid: 12, tags: ['partner'], name: "Michiels",voornaam: "Constantius",date: "1871"},
        { id: 22, pid: 13, tags: ['partner'], name: "Renders",voornaam: "Joannes Baptista",date: "23/05/1860"},
        { id: 23, pid: 14, tags: ['partner'], name: "De Mulder",voornaam: "Joannes",date: ""},
        { id: 24, pid: 15, tags: ['partner'], name: "Vanderborght",voornaam: "Maria Theresia",date: " "},
        { id: 25, pid: 11, ppid:20, name: "Peeters",voornaam: "Maria Stephania",date: "1895",tags: ["jena"] },
        { id: 26, pid: 11, ppid:20, name: "Peeters",voornaam: "Emile",date: "1898",tags: ["jena"] },
        { id: 27, pid: 11, ppid:20, name: "Peeters",voornaam: "Andreas",date: "1901",tags: ["jena"] },
        { id: 28, pid: 11, ppid:20, name: "Peeters",voornaam: "Guilielmus",date: "1904",tags: ["jena"], },
        { id: 29, pid: 11, ppid:20, name: "Peeters",voornaam: "Marie Louize",date: "1909",tags: ["jena"] },
        { id: 30, pid: 17, tags: ['partner',"verhulst"], name: "Storkels",voornaam: "Jan Baptist",date: "1887-1914"},
    ];
    michielstree = [
        { id: 1, name: "Felix", voornaam: "Jena", date: "14/01/1807-07/08/1876", beschrijving: "", tags: ["jena"]},
        { id: 16, pid: 1, tags: ["partner", "Jena"], name: "Verhulst",voornaam: "Anna Maria",date: "1802-1870"}, 
        { id: 18, pid: 3, tags: ['partner', ] , name: "Delqui",voornaam: "Joanna",date: ""},
        { id: 2, pid: 1, ppid: 16, name: "Jena",voornaam: "Joanna Maria",date: "1831-1834"},                
        { id: 3, pid: 1, ppid: 16, name: "Jena",voornaam: "Jan Baptist",date: "02/09/1835-15/02/1910"},
        { id: 4, pid: 1, ppid: 16, name: "Jena",voornaam: "Guillemin Albertus",date: "08/01/1839-16/04/1887",tags: ["jena"]},
        { id: 19, pid: 4, tags: ['partner'], name: "Delmé",voornaam: "Maria Thérésia",date: "1833-09/03/1900" },
        { id: 10, pid: 4, name: "Jena",voornaam: "Guisbertus Augustinus ",date: "1863-1867" },
        { id: 11, pid: 4, name: "Jena",voornaam: "Joanna Maria",date: "1865"},
        { id: 12, pid: 4, name: "Jena",voornaam: "Maria Theresia",date: "1866",tags: ["jena"] },
        { id: 13, pid: 4, name: "Jena",voornaam: "Maria Louisa",date: "21/05/1868" },
        { id: 14, pid: 4, name: "Jena",voornaam: "Stephania",date: "1879" },
        { id: 15, pid: 4, name: "Jena",voornaam: "Emile",date: "1878-1958" }, 
        { id: 31, pid: 12, ppid:21, name: "Michiels",voornaam: "Mathilde Amelie Marie ",date: "13/03/1894-19/12/1973 ",tags: ["jena"] },
        { id: 32, pid: 12, ppid:21, name: "Michiels",voornaam: "Maria Ludovica",date: "24/04/1897",tags: ["jena"]},
        { id: 33, pid: 12, ppid:21, name: "Michiels",voornaam: "colletta ",date: "1899 " ,tags: ["jena"]},
        { id: 34, pid: 12, ppid:21, name: "Michiels",voornaam: "Emmanuel franciscus ",date: "14/01/1902-20/08/1966 ",tags: ["jena"] },
        { id: 35, pid: 12, ppid:21, name: "Michiels",voornaam: "Maria Emerentia ",date: "18/10/1904-04/01/1968 ", tags: ["jena"]},
        { id: 36, pid: 12, ppid:21, name: "Michiels",voornaam: "Gustaaf Felix",date: "26/01/1908-27/10/1985 ",tags: ["jena"] },
        { id: 37, pid: 31, tags: ['partner',"verhulst"], name: "Vanderveeren ",voornaam: "Eugène ",date: " "},
        { id: 38, pid: 33, tags: ['partner',"oranje"], name: "Schroeders ",voornaam: "Felix ",date: " "},
        { id: 39, pid: 34, tags: ['partner',"rood"], name: " Van Geel",voornaam: "Marie Louise ",date: " "},
        { id: 40, pid: 35, tags: ['partner',"blauw"], name: "Michiels ",voornaam: "Frans",date: " "},
        { id: 41, pid: 36, tags: ['partner',"grijs"], name: "Vlaeyen ",voornaam: "Maria Julia",date: " "},
        { id: 20, pid: 11, tags: ['partner'], name: "Peeters",voornaam: "Francois August",date: "1861"},
        { id: 21, pid: 12, tags: ['partner',"verhulst"], name: "Michiels",voornaam: "Constantius",date: "1871"},
        { id: 22, pid: 13, tags: ['partner'], name: "Renders",voornaam: "Joannes Baptista",date: "23/05/1860"},
        { id: 23, pid: 14, tags: ['partner'], name: "De Mulder",voornaam: "Joannes",date: ""},
        { id: 24, pid: 15, tags: ['partner'], name: "Vanderborght",voornaam: "Maria Theresia",date: " "},
        { id: 68, pid: 31, ppid:37, name: "Vanderveeren",voornaam: "Henricus Jules ",date: "1918-1940 ",beschrijving: "gesneuveld tijdens de 18daagse veldtocht",tags: ["jena"]  },
        { id: 69, pid: 31, ppid:37, name: "Vanderveeren",voornaam: "Florentina  ",date: "03/03/1920 ",tags: ["jena"]  },
        { id: 70, pid: 31, ppid:37, name: "Vanderveeren",voornaam: " Maria ",date: "01/03/1922-09/11/2004 ",tags: ["jena"]  },
        { id: 71, pid: 31, ppid:37, name: "Vanderveeren",voornaam: "Ludovicus Felix  ",date: "1924 " ,tags: ["jena"] },
        { id: 72, pid: 31, ppid:37, name: "Vanderveeren",voornaam: "Martha Anastasia  ",date: "04/07/1933-29/06-1998 ",tags: ["jena"]  },
        { id: 73, pid: 69, tags: ['partner',"verhulst"], name: "Meddaerts ",voornaam: "Emile",date: "  "},
        { id: 74, pid: 70, tags: ['partner',"verhulst"], name: "Schroeders ",voornaam: "Jozef",date: "17/03/1925-18/09/2015"},
        { id: 75, pid: 71, tags: ['partner',"verhulst"], name: "Coopmans ",voornaam: "Anna",date: "11/04/1923-13/05/2005 "},
        { id: 76, pid: 72, tags: ['partner',"verhulst"], name: "Verstappen",voornaam: "Adelin Victor",date: "13/03/1933- "},
        { id: 77, pid: 70, ppid:74, name: "Schroeders",voornaam: "Fabienne  ",date: "04/09/1968  ",tags: ["jena"]  },
        { id: 78, pid: 71, ppid:75, name: "Vanderveeren",voornaam: "Jules  ",date: "08/08/1951",tags: ["jena"]  },
        { id: 79, pid: 71, ppid:75, name: "Vanderveeren",voornaam: "Jos  ",date: "  " ,tags: ["jena"] },
        { id: 80, pid: 71, ppid:75, name: "Vanderveeren",voornaam: "Anne-Marie  ",date: "25/06/1956",tags: ["jena"]  },
        { id: 81, pid: 72, ppid:76, name: "Verstappen",voornaam: "Karine Etienne Maria  ",date: "09/12/1964 ",tags: ["jena"]  },
        { id: 82, pid: 77, tags: ['partner',"verhulst"], name: "Schotte ",voornaam: "Kris",date: "  "},
        { id: 83, pid: 78, tags: ['partner',"verhulst"], name: "Adriaens ",voornaam: "Elianne",date: "  "},
        { id: 84, pid: 79, tags: ['partner',"verhulst"], name: "Philips ",voornaam: "Eveline",date: "19/12/1952"},
        { id: 85, pid: 80, tags: ['partner',"verhulst"], name: "Devroye ",voornaam: "Marc",date: "13/10/1959  "},
        { id: 86, pid: 81, tags: ['partner',"verhulst"], name: "Vlaeyen ",voornaam: "Jan",date: "03/02/1965  "},
        { id: 87, pid: 77, ppid:82, name: "Schotte",voornaam: "Sophie  ",date: "  ",tags: ["jena"]  },
        { id: 88, pid: 77, ppid:82, name: "Schotte",voornaam: "Anouk  ",date: " ",tags: ["jena"]  },
        { id: 89, pid: 78, ppid:83, name: "Vanderveeren",voornaam: "Ilse  ",date: "  ",tags: ["jena"]  },
        { id: 90, pid: 78, ppid:83, name: "Vanderveeren",voornaam: "Michaël  ",date: " " ,tags: ["jena"] },
        { id: 91, pid: 79, ppid:84, name: "Vanderveeren",voornaam: "Hedwige  ",date: "24/04/1978  ",tags: ["jena"]  },        
        { id: 92, pid: 80, ppid:85, name: "Devroye",voornaam: "Els  ",date: " 14/05/1981 ",tags: ["jena"]  },
        { id: 93, pid: 80, ppid:85, name: "Devroye",voornaam: "Annelies  ",date: "06/09/1982 " ,tags: ["jena"] },
        { id: 94, pid: 80, ppid:85, name: "Devroye",voornaam: "Iris  ",date: " 17/09/1987 " ,tags: ["jena"] },
        { id: 95, pid: 80, ppid:85, name: "Devroye",voornaam: "Wim  ",date: " 01/04/1989 ",tags: ["jena"]  },                
        { id: 96, pid: 81, ppid:86, name: "Vlaeyen",voornaam: "Michiel  ",date: "10/07/1994  ",tags: ["jena"]  },
        { id: 97, pid: 81, ppid:86, name: "Vlaeyen",voornaam: "Thijs  ",date: "03/01/2001",tags: ["jena"]  },
       
        
      
        { id: 98, pid: 33, ppid:38, name: "Schroeders",voornaam: "Jules  ",date: "30/04/1920-28/02/1996  ",beschrijving: "doodsbrief," ,tags: ["jena"] },
        { id: 99, pid: 98, tags: ['partner',"oranje"], name: "Teck ",voornaam: "Jeanne",date: " 18/05/1927-14/12/2019 "},
        { id: 100, pid: 98, ppid:99, name: "Schroeders",voornaam: "Willy  ",date: "  ",tags: ["jena"] },
        { id: 101, pid: 100, tags: ['partner',"oranje"], name: "De Coster ",voornaam: "Marie Rose",date: "  "},
        { id: 102, pid: 100, ppid:101, name: "Schroeders",voornaam: "Dominique  ",date: "  ",tags: ["jena"] },
        { id: 103, pid: 102, tags: ['partner',"oranje"], name: "Leffelaer  ",voornaam: "Heidi",date: "  "},


        { id: 104, pid: 34, ppid:39, name: "Michiels",voornaam: "Felix ",date: "23/08/1932-24/05/2009 ",tags: ["jena"]  },
        { id: 105, pid: 34, ppid:39, name: "Michiels",voornaam: "Maria ",date: "" ,tags: ["jena"] },
        { id: 106, pid: 34, ppid:39, name: "Michiels",voornaam: "Marie Jeanne ",date: " " ,tags: ["jena"] },
        { id: 107, pid: 104, tags: ['partner',"rood"], name: "De De Greef ",voornaam: "Margriet",date: "  "},
        { id: 108, pid: 105, tags: ['partner',"rood"], name: "Grootjans",voornaam: "Pierre",date: " 29/04/1929-07/09/2000 "},
        { id: 109, pid: 106, tags: ['partner',"rood"], name: "Ronsmans ",voornaam: "Jean",date: " 05/01/1940-09/07/2004 "},
        { id: 110, pid: 104, ppid:107, name: "Michiels",voornaam: "Linda ",date: "  ",tags: ["jena"]  },
        { id: 111, pid: 106, ppid:109, name: "Ronsmans",voornaam: "Karine ",date: " " ,tags: ["jena"] },
        { id: 112, pid: 106, ppid:109, name: "Ronsmans",voornaam: "Anne ",date: " ",tags: ["jena"]  },
        { id: 113, pid: 110, tags: ['partner',"rood"], name: "De Coster  ",voornaam: "Luc",date: "  "},
        { id: 114, pid: 111, tags: ['partner',"rood"], name: "Feytens  ",voornaam: "Marc",date: "  "},
        { id: 115, pid: 112, tags: ['partner',"rood"], name: "Kins  ",voornaam: "Peter",date: "  "},
        { id: 116, pid: 110, ppid:113, name: "De Coster",voornaam: "Sylvia ",date: "  ",tags: ["jena"]  },
        { id: 117, pid: 111, ppid:114, name: "Feytens",voornaam: "Sanne ",date: "  ",tags: ["jena"]  },
        { id: 118, pid: 111, ppid:114, name: "Feytens",voornaam: "Kristof ",date: "  ",tags: ["jena"]  },

        { id: 119, pid: 35, ppid:40, name: "Michiels",voornaam: "Marie Louise ",date: "03/09/1927-08/08/2003  ",tags: ["jena"]  },
        { id: 120, pid: 35, ppid:40, name: "Michiels",voornaam: "Maria ",date: " 07/05/1932-06/01/1998 ",tags: ["jena"]  },
        { id: 121, pid: 35, ppid:40, name: "Michiels",voornaam: "Denise ",date: "  ",tags: ["jena"]  },
        { id: 122, pid: 35, ppid:40, name: "Michiels",voornaam: "robert ",date: "  " ,tags: ["jena"] },
        { id: 123, pid: 119, tags: ['partner',"blauw"], name: "Scherens  ",voornaam: "Philip",date: "  "},
        { id: 124, pid: 120, tags: ['partner',"blauw"], name: "Janssens  ",voornaam: "Alfons",date: "  "},
        { id: 125, pid: 121, tags: ['partner',"blauw"], name: "Van Horenbeeck  ",voornaam: "Marcel",date: "  "},
        { id: 126, pid: 122, tags: ['partner',"blauw"], name: "Raymaekers  ",voornaam: " ",date: "  "},
        { id: 127, pid: 119, ppid:123, name: "Scherens",voornaam: "Viviane",date: " ",tags: ["jena"]  },
        { id: 128, pid: 127, tags: ['partner',"blauw"], name: "Brigitta  ",voornaam: "Christophe",date: "  "},
        { id: 129, pid: 127, ppid:128, name: "Brigitta",voornaam: "Dieter",date: " ",tags: ["jena"]  },
        
        { id: 130, pid: 36, ppid:41, name: "Michiels",voornaam: "Maria Theresia ",date: "05/06/1938-03/04/2006  ",tags: ["jena"]  },
        { id: 131, pid: 36, ppid:41, name: "Michiels",voornaam: "Georges ",date: "12/08/1939  ",tags: ["jena"]  },
        { id: 132, pid: 36, ppid:41, name: "Michiels",voornaam: "André",date: "13/12/1948  ",tags: ["jena"]  },
        { id: 133, pid: 130, tags: ['partner',"grijs"], name: "Bruynickx  ",voornaam: "Francois",date: "  "},
        { id: 134, pid: 131, tags: ['partner',"grijs"], name: "Teck  ",voornaam: "Lisette",date: "  "},
        { id: 135, pid: 132, tags: ['partner',"grijs"], name: "Buggenhout",voornaam: "Sonja",date: "  "},
        { id: 136, pid: 130, ppid:133, name: "Bruyninckx",voornaam: "Nico ",date: "  ",tags: ["jena"]  },
        { id: 137, pid: 131, ppid:134, name: "Michiels",voornaam: "Nadia ",date: "13/10/1968 ",tags: ["jena"]  },
        { id: 138, pid: 136, tags: ['partner',"grijs"], name: "Quenia  ",voornaam: "Peggy",date: "  "},
        { id: 139, pid: 137, tags: ['partner',"grijs"], name: "Schrevens  ",voornaam: "Michaël",date: "  "},
        { id: 140, pid: 137, ppid:139, name: "Schrevens",voornaam: "Thomas ",date: "  ",tags: ["jena"]  },
        { id: 141, pid: 137, ppid:139, name: "Schrevens",voornaam: "Elise ",date: "  ",tags: ["jena"]  },
        { id: 142, pid: 137, ppid:139, name: "Schrevens",voornaam: "Arne ",date: "  ",tags: ["jena"]  },
        { id: 143, pid: 136, ppid:138, name: "Bruyninckx",voornaam: "Senna ",date: "  ",tags: ["jena"]  },
        { id: 144, pid: 136, ppid:138, name: "Bruyninckx",voornaam: "Luka ",date: "  ",tags: ["jena"]  },

        { id: 145, pid: 91, tags: ['partner',"verhulst"], name: "Adriaensen ",voornaam: "Flor",date: "11/01/1980"},
        { id: 146, pid: 91, ppid:145, name: "Adriaensen",voornaam: "Fien",date: "07/10/2008",tags: ["jena"]  },
        { id: 147, pid: 91, ppid:145, name: "Adriaensen",voornaam: "Klaar",date: "20/08/2010",tags: ["jena"]  },
        { id: 148, pid: 91, ppid:145, name: "Adriaensen",voornaam: "Nand",date: "10/08/2013" ,tags: ["jena"] },
        { id: 149, pid: 92, tags: ['partner',"verhulst"], name: "Torfs",voornaam: "Stijn",date: " "},
        { id: 150, pid: 92, ppid:149, name: "Torfs",voornaam: "Arthur",date: "16/05/2019",tags: ["jena"]  },
        { id: 151, pid: 92, ppid:149, name: "Torfs",voornaam: "Victor",date: "30/07/2020",tags: ["jena"]  },
    ];
    renderstree = [
         { id: 1, name: "Felix", voornaam: "Jena", date: "14/01/1807-07/08/1876", beschrijving: "", tags: ["jena"]},
         { id: 16, pid: 1, tags: ["partner", "Jena"], name: "Verhulst",voornaam: "Anna Maria",date: "1802-1870"}, 
         { id: 18, pid: 3, tags: ['partner', ] , name: "Delqui",voornaam: "Joanna",date: ""},
         { id: 2, pid: 1, ppid: 16, name: "Jena",voornaam: "Joanna Maria",date: "1831-1834"},                
         { id: 3, pid: 1, ppid: 16, name: "Jena",voornaam: "Jan Baptist",date: "02/09/1835-15/02/1910"},
         { id: 4, pid: 1, ppid: 16, name: "Jena",voornaam: "Guillemin Albertus",date: "08/01/1839-16/04/1887",tags: ["jena"]},
         { id: 19, pid: 4, tags: ['partner'], name: "Delmé",voornaam: "Maria Thérésia",date: "1833-09/03/1900" },
         { id: 10, pid: 4, name: "Jena",voornaam: "Guisbertus Augustinus ",date: "1863-1867" },
         { id: 11, pid: 4, name: "Jena",voornaam: "Joanna Maria",date: "1865"},
         { id: 12, pid: 4, name: "Jena",voornaam: "Maria Theresia",date: "1866" },
         { id: 13, pid: 4, name: "Jena",voornaam: "Maria Louisa",date: "21/05/1868",tags: ["jena"] },
         { id: 14, pid: 4, name: "Jena",voornaam: "Stephania",date: "1879" },
         { id: 15, pid: 4, name: "Jena",voornaam: "Emile",date: "1878-1958" },
         { id: 17, pid: 11, ppid:20, name: "Peeters",voornaam: "Maria Theresia",date: "20/05/1890-1914" },
         { id: 20, pid: 11, tags: ['partner'], name: "Peeters",voornaam: "Francois August",date: "1861"},
         { id: 21, pid: 12, tags: ['partner'], name: "Michiels",voornaam: "Constantius",date: "1871"},
         { id: 22, pid: 13, tags: ['partner',"verhulst"], name: "Renders",voornaam: "Joannes Baptista",date: "23/05/1860"},
         { id: 23, pid: 14, tags: ['partner'], name: "De Mulder",voornaam: "Joannes",date: ""},
         { id: 24, pid: 15, tags: ['partner'], name: "Vanderborght",voornaam: "Maria Theresia",date: " "},
         { id: 42, pid: 13, ppid:22, name: "Renders",voornaam: "Joanna Marie ",date: "13/08/1896-07/01/1986",tags: ["jena"] },
        { id: 43, pid: 13, ppid:22, name: "Renders",voornaam: "Constantius ",date: "  " ,tags: ["jena"]},
        { id: 44, pid: 13, ppid:22, name: "Renders",voornaam: "Victor ",date: "  ",tags: ["jena"] },
        { id: 45, pid: 13, ppid:22, name: "Renders",voornaam: "Marie Theresia",date: "  ",tags: ["jena"] },
        { id: 46, pid: 13, ppid:22, name: "Renders",voornaam: "Bertha ",date: "  ",tags: ["jena"] },
        { id: 47, pid: 13, ppid:22, name: "Renders",voornaam: "Alfons",date: "  ",tags: ["jena"] },   
        { id: 152, pid: 42, tags: ['partner',"oranje"], name: "Vandenput",voornaam: "Joannes Alfons",date: " "},
        { id: 153, pid: 42, ppid:152, name: "Vandenput",voornaam: "Valerie ",date: "",tags: ["jena"] },
        { id: 154, pid: 42, ppid:152, name: "Vandenput",voornaam: "Bertha ",date: "",tags: ["jena"] },
        { id: 155, pid: 42, ppid:152, name: "Vandenput",voornaam: " Mariette",date: "" ,tags: ["jena"]},
        { id: 156, pid: 42, ppid:152, name: "Vandenput",voornaam: "Ghislaine ",date: "" ,tags: ["jena"]},
        { id: 157, pid: 42, ppid:152, name: "Vandenput",voornaam: " René",date: "",tags: ["jena"] },
        { id: 158, pid: 153, tags: ['partner',"oranje"], name: "Lefever ",voornaam: " Victor",date: " "},
        { id: 159, pid: 154, tags: ['partner',"oranje"], name: "Goossens ",voornaam: " Remy",date: " "},    
        { id: 160, pid: 155, tags: ['partner',"oranje"], name: "Letellier ",voornaam: " Jozef",date: " "},
        { id: 161, pid: 156, tags: ['partner',"oranje"], name: "Goossens ",voornaam: "Gerard ",date: " "},
        { id: 162, pid: 157, tags: ['partner',"oranje"], name: "Morel",voornaam: "Marie-Rose ",date: " "},
        { id: 163, pid: 153, ppid:158, name: "Lefever",voornaam: " Marie-Louize",date: "",tags: ["jena"] },
        { id: 164, pid: 153, ppid:158, name: "Lefever",voornaam: " Anita",date: "",tags: ["jena"] },
        { id: 165, pid: 153, ppid:158, name: "Lefever",voornaam: " Maggy",date: "" ,tags: ["jena"]},
        { id: 166, pid: 153, ppid:158, name: "Lefever",voornaam: " Christiane",date: "",tags: ["jena"] },
        { id: 167, pid: 163, tags: ['partner',"oranje"], name: "Adriaens",voornaam: "Henri",date: " "},
        { id: 168, pid: 164, tags: ['partner',"oranje"], name: "De Broyer",voornaam: "Felix ",date: " "},
        { id: 169, pid: 165, tags: ['partner',"oranje"], name: "Vanhaute",voornaam: "Jan ",date: " "},
        { id: 170, pid: 166, tags: ['partner',"oranje"], name: "Vanhaute",voornaam: "Jos ",date: " "},
        { id: 171, pid: 154, ppid:159, name: "Goossens",voornaam: " André",date: "",tags: ["jena"] }, 
        { id: 172, pid: 154, ppid:159, name: "Goossens",voornaam: " Josephine",date: "",tags: ["jena"] },
        { id: 173, pid: 171, tags: ['partner',"oranje"], name: "Vanmessom",voornaam: "Clara",date: " "},
        { id: 174, pid: 172, tags: ['partner',"oranje"], name: "Bauwens",voornaam: "Emile",date: " "},
        { id: 175, pid: 155, ppid:160, name: "Letellier",voornaam: " Agnes",date: "",tags: ["jena"] },
        { id: 176, pid: 155, ppid:160, name: "Letellier",voornaam: " Maria",date: "" ,tags: ["jena"]},
        { id: 177, pid: 155, ppid:160, name: "Letellier",voornaam: " Anny",date: "" ,tags: ["jena"]},
        { id: 178, pid: 155, ppid:160, name: "Letellier",voornaam: " Ingrid",date: "",tags: ["jena"] },    
        { id: 179, pid: 175, tags: ['partner',"oranje"], name: "Vanpee",voornaam: "René",date: " "},     
        { id: 180, pid: 176, tags: ['partner',"oranje"], name: "Lahaye",voornaam: "Michel",date: " "},
        { id: 181, pid: 177, tags: ['partner',"oranje"], name: "Michiels",voornaam: "Jacques",date: " "},
        { id: 182, pid: 156, ppid:161, name: "Goossens",voornaam: " Marleen",date: "",tags: ["jena"] },
        { id: 183, pid: 156, ppid:161, name: "Goossens",voornaam: " Guido",date: "",tags: ["jena"] },
        { id: 184, pid: 156, ppid:161, name: "Goossens",voornaam: " Kristien",date: "" ,tags: ["jena"]},
        { id: 185, pid: 182, tags: ['partner',"oranje"], name: "Vanderlinden",voornaam: "Ivo",date: " "},
        { id: 186, pid: 157, ppid:162, name: "Vandenput",voornaam: " Joëlle",date: "",tags: ["jena"] },
        { id: 187, pid: 157, ppid:162, name: "Vandenput",voornaam: " Olivier",date: "",tags: ["jena"] },
        { id: 188, pid: 157, ppid:162, name: "Vandenput",voornaam: " Christophe",date: "",tags: ["jena"] },
        { id: 189, pid: 45, tags: ['partner',"rood"], name: "Vande Velde",voornaam: "Jan",date: " "},
        { id: 190, pid: 45, ppid:189, name: "Vande Velde",voornaam: " Frans",date: "28/02/1931-25/10/2020",tags: ["jena"] },
        { id: 191, pid: 190, name: "Vande Velde",voornaam: " Chris",date: "",tags: ["jena"] },   
        { id: 192, pid: 190, name: "Vande Velde",voornaam: " Freddy",date: "" ,tags: ["jena"]},
        { id: 193, pid: 190, name: "Vande Velde",voornaam: " Marie-Thérèse",date: "",tags: ["jena"] },
        { id: 194, pid: 191, tags: ['partner',"rood"], name: "  ",voornaam: "Veronique",date: " "},
        { id: 195, pid: 192, tags: ['partner',"rood"], name: "",voornaam: "Gaby",date: " "},
        { id: 196, pid: 193, tags: ['partner',"rood"], name: "Goossens ",voornaam: "Jean-Louis",date: " "},
        { id: 197, pid: 191, ppid:194, name: "Vande Velde",voornaam: " Gertjan",date: "",tags: ["jena"] },
        { id: 198, pid: 191, ppid:194, name: "Vande Velde",voornaam: " Laurien",date: "",tags: ["jena"] },
        { id: 199, pid: 192, ppid:195, name: "Vande Velde",voornaam: " Joris",date: "",tags: ["jena"] },
        { id: 200, pid: 192, ppid:195, name: "Vande Velde",voornaam: " Mats",date: "",tags: ["jena"] },
    ];
    demuldertree = [
        { id: 1, name: "Felix", voornaam: "Jena", date: "14/01/1807-07/08/1876", beschrijving: "", tags: ["jena"]},
        { id: 16, pid: 1, tags: ["partner", "Jena"], name: "Verhulst",voornaam: "Anna Maria",date: "1802-1870"}, 
        { id: 18, pid: 3, tags: ['partner',  ] , name: "Delqui",voornaam: "Joanna",date: ""},
        { id: 2, pid: 1, ppid: 16, name: "Jena",voornaam: "Joanna Maria",date: "1831-1834"},                
        { id: 3, pid: 1, ppid: 16, name: "Jena",voornaam: "Jan Baptist",date: "02/09/1835-15/02/1910"},
        { id: 4, pid: 1, ppid: 16, name: "Jena",voornaam: "Guillemin Albertus",date: "08/01/1839-16/04/1887",tags: ["jena"]},
        { id: 19, pid: 4, tags: ['partner'], name: "Delmé",voornaam: "Maria Thérésia",date: "1833-09/03/1900" },
        { id: 10, pid: 4, name: "Jena",voornaam: "Guisbertus Augustinus ",date: "1863-1867" },
        { id: 11, pid: 4, name: "Jena",voornaam: "Joanna Maria",date: "1865"},
        { id: 12, pid: 4, name: "Jena",voornaam: "Maria Theresia",date: "1866" },
        { id: 13, pid: 4, name: "Jena",voornaam: "Maria Louisa",date: "21/05/1868" },
        { id: 14, pid: 4, name: "Jena",voornaam: "Stephania",date: "1879",tags: ["jena"] },
        { id: 15, pid: 4, name: "Jena",voornaam: "Emile",date: "1878-1958" },
        { id: 17, pid: 11, ppid:20, name: "Peeters",voornaam: "Maria Theresia",date: "20/05/1890-1914" },
        { id: 20, pid: 11, tags: ['partner'], name: "Peeters",voornaam: "Francois August",date: "1861"},
        { id: 21, pid: 12, tags: ['partner'], name: "Michiels",voornaam: "Constantius",date: "1871"},
        { id: 22, pid: 13, tags: ['partner'], name: "Renders",voornaam: "Joannes Baptista",date: "23/05/1860"},
        { id: 23, pid: 14, tags: ['partner',"oranje"], name: "De Mulder",voornaam: "Joannes",date: ""},
        { id: 24, pid: 15, tags: ['partner'], name: "Vanderborght",voornaam: "Maria Theresia",date: " "},  
        { id: 48, pid: 14, ppid:23, name: "De Mulder",voornaam: "Constantius  ",date: "02/05/1899 ",tags: ["jena"] },
        { id: 49, pid: 14, ppid:23, name: "De Mulder",voornaam: "Virginia ",date: "03/02/1901 ",tags: ["jena"] },
        { id: 50, pid: 14, ppid:23, name: "De Mulder",voornaam: " Joris ",date: "27/12/1904 " ,tags: ["jena"]},
        { id: 51, pid: 14, ppid:23, name: "De Mulder",voornaam: "Andreas  ",date: "16/08/1907 ",tags: ["jena"] },
    ];    
    jenatree = [
        { id: 1, name: "Felix", voornaam: "Jena", date: "14/01/1807-07/08/1876", beschrijving: "", tags: ["jena"]},
        { id: 16, pid: 1, tags: ["partner", "Jena"], name: "Verhulst",voornaam: "Anna Maria",date: "1802-1870"}, 
        { id: 18, pid: 3, tags: ['partner', ] , name: "Delqui",voornaam: "Joanna",date: ""},
        { id: 2, pid: 1, ppid: 16, name: "Jena",voornaam: "Joanna Maria",date: "1831-1834"},                
        { id: 3, pid: 1, ppid: 16, name: "Jena",voornaam: "Jan Baptist",date: "02/09/1835-15/02/1910"},
        { id: 4, pid: 1, ppid: 16, name: "Jena",voornaam: "Guillemin Albertus",date: "08/01/1839-16/04/1887",tags: ["jena"]},
        { id: 19, pid: 4, tags: ['partner'], name: "Delmé",voornaam: "Maria Thérésia",date: "1833-09/03/1900" },
        { id: 10, pid: 4, name: "Jena",voornaam: "Guisbertus Augustinus ",date: "1863-1867" },
        { id: 11, pid: 4, name: "Jena",voornaam: "Joanna Maria",date: "1865"},
        { id: 12, pid: 4, name: "Jena",voornaam: "Maria Theresia",date: "1866" },
        { id: 13, pid: 4, name: "Jena",voornaam: "Maria Louisa",date: "21/05/1868" },
        { id: 14, pid: 4, name: "Jena",voornaam: "Stephania",date: "1879" },
        { id: 15, pid: 4, name: "Jena",voornaam: "Emile",date: "1878-1958",tags: ["jena"]},
        { id: 17, pid: 11, ppid:20, name: "Peeters",voornaam: "Maria Theresia",date: "20/05/1890-1914" },
        { id: 20, pid: 11, tags: ['partner'], name: "Peeters",voornaam: "Francois August",date: "1861"},
        { id: 21, pid: 12, tags: ['partner'], name: "Michiels",voornaam: "Constantius",date: "1871"},
        { id: 22, pid: 13, tags: ['partner'], name: "Renders",voornaam: "Joannes Baptista",date: "23/05/1860"},
        { id: 23, pid: 14, tags: ['partner'], name: "De Mulder",voornaam: "Joannes",date: ""},
        { id: 24, pid: 15, tags: ['partner',"verhulst"], name: "Vanderborght",voornaam: "Maria Theresia",date: " "}, 
        { id: 53, pid: 15, ppid:24, name: "Jena",voornaam: "Petrus Arthur ",date: "08/07/1906-23/06/1948 ",tags: ["jena"] },
        { id: 52, pid: 15, ppid:24, name: "Jena",voornaam: "Stan ",date: "1904 ",tags: ["jena"] },
        { id: 54, pid: 53, tags: ['partner',"oranje"], name: "Delblaere ",voornaam: "Martha",date: "1908-2000 "},
        { id: 55, pid: 53, ppid:54, name: "Jena",voornaam: "Willy  ",date: "1932-2017  " ,tags: ["jena"]},
        { id: 56, pid: 53, ppid:54, name: "Jena",voornaam: "Hugo joris ",date: "22/10/1938  ",tags: ["jena"] },
        { id: 57, pid: 53, ppid:54, name: "Jena",voornaam: "Hedwig  ",date: "1946  ",tags: ["jena"] },
        { id: 58, pid: 55, tags: ['partner',"rood"], name: "Vloebergh",voornaam: "Irene",date: "1930-2016 "},
        { id: 59, pid: 55, tags: ['partner',"blauw"], name: "Dullaerts ",voornaam: "Lilianne",date: ""},
        { id: 60, pid: 57, tags: ['partner',"grijs"], name: "Endels ",voornaam: "Lucienne",date: "1948 "},
        { id: 61, pid: 55, ppid:58, name: "Jena",voornaam: "Dirk  ",date: "  ",tags: ["jena"] },
        { id: 62, pid: 55, ppid:59, name: "Jena",voornaam: "Michaël  ",date: "29-03-1982  ",tags: ["jena"] },
        { id: 63, pid: 61, tags: ['partner',"rood"], name: "De Wilde",voornaam: "Ingrid",date: " "},
        { id: 64, pid: 62, tags: ['partner',"blauw"], name: "Mullens",voornaam: "Cindy",date: "25/05/1984 "},
        { id: 65, pid: 61, ppid:63, name: "Jena",voornaam: "Tuur  ",date: "13/07/1986  ",tags: ["jena"]},
        { id: 66, pid: 61, ppid:63, name: "Jena",voornaam: "Fons  ",date: "11/01/1989  ",tags: ["jena"] },
        { id: 67, pid: 62, ppid:64, name: "Jena",voornaam: "Pjotr ",date: " 17/03/2017 ",tags: ["jena"] },
    ];

    chart.load(jenaoorsprongtree);
}

function jenaoorsprong() {
    chart.load(jenaoorsprongtree);
}

function peeters() {
    chart.load(peeterstree)
}

function michiels() {
    chart.load(michielstree);    
}

function renders() {
    chart.load(renderstree);    
}

function demulder() {
    chart.load(demuldertree);    
}

function jena() {
    chart.load(jenatree);    
}